version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: fastapi_server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres_db:5432/postgres
    ports:
      - "8080:8080"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - my_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  networks:
    my_network:

  volumes:
    postgres_data: